[build-system]
requires = [
    "setuptools>=42",
    "numpy",
    "math",
    "pygame",
    "random",
    "time",
    "os",
    "collections",
    "typing",
    "colorsys"
]
build-backend = "setuptools.build_meta"